QLRCP:
	g++ -std=c++11 Employee.cpp EmployeeList.cpp employeemain.cpp drawTable.cpp splitStringByWords.cpp gotoXY.cpp ActionMovie.cpp AnimatedMovie.cpp HorrorMovie.cpp LoveMovie.cpp Movie.cpp MovieList.cpp ShowTime.cpp Datetime.cpp Chair.cpp displayChairs.cpp Customer.cpp CustomerList.cpp Color.cpp -o employeemain
	./employeemain